/**
 * Covid19 Tests API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';

export interface DefaultFormDto { 
    firstname: string;
    lastname: string;
    gender: DefaultFormDto.GenderEnum;
    bday: string;
    phoneNumber?: string;
    address?: AddressDto;
    editor?: string;
    mobile?: boolean;
    testAddressNote?: string;
    contactSeverity?: string;
    comment?: string;
}
export namespace DefaultFormDto {
    export type GenderEnum = 'M' | 'W' | 'D';
    export const GenderEnum = {
        M: 'M' as GenderEnum,
        W: 'W' as GenderEnum,
        D: 'D' as GenderEnum
    };
}