/**
 * Covid19 Tests API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';

export interface PatientDto { 
    occupationGroup?: string;
    firstname: string;
    lastname: string;
    gender: PatientDto.GenderEnum;
    bday: string;
    address: AddressDto;
    phoneNumber: string;
    healthCareOrganisationNumber?: string;
    personalHealthCareNumber?: string;
    insuranceType: string;
    mobile?: boolean;
}
export namespace PatientDto {
    export type GenderEnum = 'M' | 'W' | 'D';
    export const GenderEnum = {
        M: 'M' as GenderEnum,
        W: 'W' as GenderEnum,
        D: 'D' as GenderEnum
    };
}