/**
 * Covid19 Tests API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChangePasswordDto } from './changePasswordDto';
import { SettingsDto } from './settingsDto';

export interface UserDto { 
    username: string;
    passwordDto?: ChangePasswordDto;
    settings: SettingsDto;
    role?: UserDto.RoleEnum;
    isActive?: boolean;
}
export namespace UserDto {
    export type RoleEnum = 'DEFAULT' | 'ADMIN';
    export const RoleEnum = {
        DEFAULT: 'DEFAULT' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}